name: 🦁 Game Server Build
'on':
  workflow_dispatch: {}
  push:
    paths:
      - 'game-server-race-control/**'
defaults:
  run:
    working-directory: game-server-race-control
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: build-race-control-game-server
          path: |
            game-server-race-control/package.json
            game-server-race-control/package-lock.json
            game-server-race-control/dist/
  deploy-heroku:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_GAME_SERVER}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "game-server-race-control"