name: 🦁 Server Heroku Deploy
'on':
  workflow_dispatch: {}
  push:
    paths:
      - 'game-server-race-control/**'
    branches:
      - 'main'
defaults:
  run:
    working-directory: game-server-race-control
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "game-server-race-control"